/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import controladores.HistorialControlador;
import dto.AtencionClinicaDTO;
import dto.ConsultaDTO;
import dto.VacunaDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controladores.MascotaControlador;
import dto.MascotaDTO;

/**
 *
 * @author BrayanOcampo
 */
public class VentanaHistorial extends javax.swing.JFrame {

    private HistorialControlador historialControlador;
    private MascotaControlador mascotaControlador;
    private VentanaServicios menu;
    /**
     * Creates new form HistorialClinico
     */
    public VentanaHistorial(VentanaServicios menu) {
        this.menu = menu;
        initComponents();
        setTitle("Historial");
        setLocationRelativeTo(null);
        this.historialControlador = new HistorialControlador();
        this.mascotaControlador = new MascotaControlador();
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"ID mascota","Nombre","Tipo", "Fecha", "Diagnostico", "Tratamiento","Vacuna", "Dosis", "Veterinario"}, 0);
        tablaHistorial.setModel(modelo);
    }
    
   public void mostrarHistorial(String id) {
    ArrayList<AtencionClinicaDTO> historial = historialControlador.filtrarAtencionesPorIdMascota(id);
    DefaultTableModel modelo = (DefaultTableModel) tablaHistorial.getModel();
    modelo.setRowCount(0);

    String nombreMascota = "";
    String propietarioMascota = "";
    MascotaDTO mascota = mascotaControlador.buscarMascota(id);
    if (mascota != null) {
        nombreMascota = mascota.getNombre();
        propietarioMascota = mascota.getDocumentoProp();
    }

    for (AtencionClinicaDTO atencion : historial) {
        String tipo = "";
        String diagnostico = "";
        String tratamiento = "";
        String nomVacuna = "";
        String dosis = "";

        if (atencion instanceof ConsultaDTO consulta) {
            tipo = "Consulta";
            diagnostico = consulta.getDiagnostico();
            tratamiento = consulta.getTratamiento();
        } else if (atencion instanceof VacunaDTO vacuna) {
            tipo = "Vacuna";
            nomVacuna = vacuna.getTipoVacuna();
            dosis = vacuna.getDosis();
        }

        modelo.addRow(new Object[] {
            atencion.getIdMascota(),
            nombreMascota,
            tipo,
            atencion.getFecha(),
            diagnostico,
            tratamiento,
            nomVacuna,
            dosis,
            atencion.getNombreVeterinario(),
            propietarioMascota
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        panelSec = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        lblIDMasc = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        bttDesplegarHistorial = new javax.swing.JButton();
        bttMenu = new javax.swing.JButton();
        bttMostrarDetalles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(204, 255, 255));

        lblTittle.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        lblTittle.setText("Historial");

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHistorial);

        lblIDMasc.setText("ID mascota:");

        bttDesplegarHistorial.setText("Desplegar historial");
        bttDesplegarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDesplegarHistorialActionPerformed(evt);
            }
        });

        bttMenu.setText("Menu");
        bttMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMenuActionPerformed(evt);
            }
        });

        bttMostrarDetalles.setText("Mostrar detalles");
        bttMostrarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMostrarDetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSecLayout = new javax.swing.GroupLayout(panelSec);
        panelSec.setLayout(panelSecLayout);
        panelSecLayout.setHorizontalGroup(
            panelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(lblIDMasc)
                .addGap(18, 18, 18)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(bttDesplegarHistorial)
                .addGap(68, 68, 68)
                .addComponent(bttMostrarDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addComponent(bttMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelSecLayout.setVerticalGroup(
            panelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecLayout.createSequentialGroup()
                .addGroup(panelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSecLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIDMasc)))
                    .addGroup(panelSecLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttDesplegarHistorial)
                            .addComponent(bttMostrarDetalles))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttMenu))
        );

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTittle)
                .addGap(301, 301, 301))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTittle)
                .addGap(18, 18, 18)
                .addComponent(panelSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttDesplegarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDesplegarHistorialActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText().trim();
        if (!id.isEmpty()) {
            mostrarHistorial(id);
        } else {
            JOptionPane.showMessageDialog(null, "Ingresa un ID de mascota válido.");
        }
    }//GEN-LAST:event_bttDesplegarHistorialActionPerformed

    private void bttMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_bttMenuActionPerformed

    private void bttMostrarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMostrarDetallesActionPerformed
        // TODO add your handling code here:
    int filaSeleccionada = tablaHistorial.getSelectedRow();
    // Verifica si hay una fila seleccionada
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(null, "Selecciona una fila primero.");
        return;
    }
    // Lee el tipo desde la tabla
    String tipo = tablaHistorial.getValueAt(filaSeleccionada, 2).toString();
    // Muestra datos según el tipo
    if (tipo.equals("Consulta")) {
        String diagnostico = tablaHistorial.getValueAt(filaSeleccionada, 4).toString();
        String tratamiento = tablaHistorial.getValueAt(filaSeleccionada, 5).toString();
        JOptionPane.showMessageDialog(null, "Consulta: \nDiagnóstico: " + diagnostico + "\nTratamiento: " + tratamiento);
    } else if (tipo.equals("Vacuna")) {
        String tipoVacuna = tablaHistorial.getValueAt(filaSeleccionada, 6).toString();
        String dosis = tablaHistorial.getValueAt(filaSeleccionada, 7).toString();
        JOptionPane.showMessageDialog(null, "Vacuna:\nTipo de Vacuna: " + tipoVacuna + "\nDosis: " + dosis);
    } else {
        JOptionPane.showMessageDialog(null, "Tipo de atención no reconocido.");
    }
    }//GEN-LAST:event_bttMostrarDetallesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton bttDesplegarHistorial;
    private javax.swing.JButton bttMenu;
    private javax.swing.JButton bttMostrarDetalles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDMasc;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel panelSec;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
