/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author BrayanOcampo
 */
public class VentanaServicios extends javax.swing.JFrame {

    private VentanaPrincipal menu;
    private VentanaMedicina ventanaMedicina;
    private VentanaVacuna ventanaVacuna;
<<<<<<< HEAD
=======
    private VentanaHistorial ventanaHistorial;
>>>>>>> 5135cb6208e66fab6ac5b2201e395cec78a1b875
    /**
     * Creates new form VentanaServicios
     */
    public VentanaServicios(VentanaPrincipal menu) {
        this.menu = menu;
        initComponents();
        iniciarCarga();
        setTitle("Servicios");
        setSize(700, 500);
        setLocationRelativeTo(this);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setVisible(true);
        VentanaVacuna ventanaVacuna = new VentanaVacuna(this);
        VentanaMedicina ventanaMedicina = new VentanaMedicina(this);
<<<<<<< HEAD
=======
        VentanaHistorial ventanaHistorial = new VentanaHistorial(this);
>>>>>>> 5135cb6208e66fab6ac5b2201e395cec78a1b875

        // Crear el nodo raíz del árbol con el nombre "Carpeta"
        DefaultMutableTreeNode carpeta = new DefaultMutableTreeNode("Carpeta");

        // Crear nodos hijos para los diferentes servicios
        DefaultMutableTreeNode medicina = new DefaultMutableTreeNode("Medicina General");
        DefaultMutableTreeNode vacuna = new DefaultMutableTreeNode("Vacuna");
<<<<<<< HEAD
=======
        DefaultMutableTreeNode historial = new DefaultMutableTreeNode("Historial");
>>>>>>> 5135cb6208e66fab6ac5b2201e395cec78a1b875
        DefaultMutableTreeNode salir = new DefaultMutableTreeNode("Salir");

        // Agregar los nodos hijos al nodo raíz (carpeta)
        carpeta.add(medicina);
        carpeta.add(vacuna);
<<<<<<< HEAD
=======
        carpeta.add(historial);
>>>>>>> 5135cb6208e66fab6ac5b2201e395cec78a1b875
        carpeta.add(salir);

        // Crear el modelo del árbol usando el nodo raíz y asignarlo al JTree
        DefaultTreeModel modelo = new DefaultTreeModel(carpeta);
        serviciosMenu.setModel(modelo);

        // Agregar un listener para detectar clics del mouse sobre el árbol
        serviciosMenu.addMouseListener(new MouseAdapter() {

    @Override
    public void mouseClicked(MouseEvent evt) {
        // Obtener el nodo sobre el cual se hizo clic usando la posición del mouse
        TreePath path = serviciosMenu.getPathForLocation(evt.getX(), evt.getY());

        // Verificar si se hizo clic sobre un nodo válido (no fuera del árbol)
        if (path != null) {
            // Obtener el texto del nodo seleccionado
            String nodoSeleccionado = path.getLastPathComponent().toString();

            // Evaluar qué nodo fue seleccionado y ejecutar la acción correspondiente
            switch (nodoSeleccionado) {
                
                // Abrir la ventana para servicios de medicina general
                case "Medicina General" ->  ventanaMedicina.setVisible(true);
                    
                // Abrir la ventana para servicios de vacunación
                case "Vacuna" -> ventanaVacuna.setVisible(true);
<<<<<<< HEAD
                   
                // Cerrar la ventana
                case "Salir" -> VentanaServicios.this.dispose();
                    
                    
=======
                
                // Abrir la ventana para historial clinico
                case "Historial" -> ventanaHistorial.setVisible(true);
                   
                // Cerrar la ventana
                case "Salir" -> VentanaServicios.this.dispose();
>>>>>>> 5135cb6208e66fab6ac5b2201e395cec78a1b875
            }
        }
    }
});

}

    private void iniciarCarga() {
        barraCarga.setMinimum(0);
        barraCarga.setMaximum(100);
        barraCarga.setStringPainted(true);
        barraCarga.setForeground(Color.BLUE); // Color azul

    new Thread(() -> {
        for (int i = 0; i <= 100; i++) {
            barraCarga.setValue(i);
            try {
                Thread.sleep(50);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        barraCarga.setVisible(false);
    }).start();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviciosMenu = new javax.swing.JTree();
        bttMenu = new javax.swing.JButton();
        barraCarga = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblTittle.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        lblTittle.setText("Servicios Clinica");

        separador.setBackground(new java.awt.Color(0, 0, 0));
        separador.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setViewportView(serviciosMenu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 421, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bttMenu.setBackground(new java.awt.Color(225, 225, 225));
        bttMenu.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        bttMenu.setText("Menú");
        bttMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(lblTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttMenu)
                .addGap(55, 55, 55))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTittle)
                    .addComponent(bttMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barraCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barraCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_bttMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraCarga;
    private javax.swing.JButton bttMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JSeparator separador;
    private javax.swing.JTree serviciosMenu;
    // End of variables declaration//GEN-END:variables
}
